#  This file is part of file-header-check, a command-line tool and GitHub action for checking file headers.
#  Copyright (C) 2024 Maximilian Pilz
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; version 2.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

name: 'file-header-check'
description: 'GitHub action to check whether specified files contain a header matching a given regular expression'
branding:
  color: green
  icon: file-text
inputs:
  config:
    description: 'The config file to be used'
    required: true
  config-encoding:
    description: 'The encoding of the config file for reading the config file'
    required: true
  log-level:
    description: 'The log level to be used'
    required: false
    default: 'WARNING'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: python check.py ${{ inputs.config }} -e ${{ inputs.config-encoding }} -ll ${{ inputs.log-level }}
      shell: bash